spring:
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:databaseprojectprod
    username: userprod
    password: passwdprod
    driverClassName: oracle.jdbc.driver.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect

global:
  variable:
    see: DONT Change in production environment
